/*-
 * ========================START=================================
 * UCGDisplay :: Native :: Input
 * %%
 * Copyright (C) 2018 - 2019 Universal Character/Graphics display library
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Lesser Public License for more details.
 * 
 * You should have received a copy of the GNU General Lesser Public
 * License along with this program.  If not, see
 * <http://www.gnu.org/licenses/lgpl-3.0.html>.
 * =========================END==================================
 */
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ibasco_ucgdisplay_core_input_InputDeviceManager */

#ifndef _Included_com_ibasco_ucgdisplay_core_input_InputDeviceManager
#define _Included_com_ibasco_ucgdisplay_core_input_InputDeviceManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ibasco_ucgdisplay_core_input_InputDeviceManager
 * Method:    startInputEventMonitor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ibasco_ucgdisplay_core_input_InputDeviceManager_startInputEventMonitor
  (JNIEnv *, jclass);

/*
 * Class:     com_ibasco_ucgdisplay_core_input_InputDeviceManager
 * Method:    stopInputEventMonitor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ibasco_ucgdisplay_core_input_InputDeviceManager_stopInputEventMonitor
  (JNIEnv *, jclass);

/*
 * Class:     com_ibasco_ucgdisplay_core_input_InputDeviceManager
 * Method:    refreshDeviceCache
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ibasco_ucgdisplay_core_input_InputDeviceManager_refreshDeviceCache
  (JNIEnv *, jclass);

/*
 * Class:     com_ibasco_ucgdisplay_core_input_InputDeviceManager
 * Method:    queryDevice
 * Signature: (Ljava/lang/String;)Lcom/ibasco/ucgdisplay/core/input/InputDevice;
 */
JNIEXPORT jobject JNICALL Java_com_ibasco_ucgdisplay_core_input_InputDeviceManager_queryDevice
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_ibasco_ucgdisplay_core_input_InputDeviceManager
 * Method:    getInputDevices
 * Signature: ()[Lcom/ibasco/ucgdisplay/core/input/InputDevice;
 */
JNIEXPORT jobjectArray JNICALL Java_com_ibasco_ucgdisplay_core_input_InputDeviceManager_getInputDevices
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_ibasco_ucgdisplay_core_input_InputDeviceManager_DeviceStateEventListener */

#ifndef _Included_com_ibasco_ucgdisplay_core_input_InputDeviceManager_DeviceStateEventListener
#define _Included_com_ibasco_ucgdisplay_core_input_InputDeviceManager_DeviceStateEventListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_ibasco_ucgdisplay_core_input_InputDeviceManager_RawInputEventListener */

#ifndef _Included_com_ibasco_ucgdisplay_core_input_InputDeviceManager_RawInputEventListener
#define _Included_com_ibasco_ucgdisplay_core_input_InputDeviceManager_RawInputEventListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
