/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ibasco_pidisplay_core_gpio_GpioEventService */

#ifndef _Included_com_ibasco_pidisplay_core_gpio_GpioEventService
#define _Included_com_ibasco_pidisplay_core_gpio_GpioEventService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ibasco_pidisplay_core_gpio_GpioEventService
 * Method:    startListening
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ibasco_pidisplay_core_gpio_GpioEventService_startListening
  (JNIEnv *, jclass);

/*
 * Class:     com_ibasco_pidisplay_core_gpio_GpioEventService
 * Method:    stoptListening
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ibasco_pidisplay_core_gpio_GpioEventService_stoptListening
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
