/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ibasco_pidisplay_core_system_InputDeviceManager */

#ifndef _Included_com_ibasco_pidisplay_core_system_InputDeviceManager
#define _Included_com_ibasco_pidisplay_core_system_InputDeviceManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ibasco_pidisplay_core_system_InputDeviceManager
 * Method:    startMonitor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ibasco_pidisplay_core_system_InputDeviceManager_startMonitor
  (JNIEnv *, jclass);

/*
 * Class:     com_ibasco_pidisplay_core_system_InputDeviceManager
 * Method:    stopMonitor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ibasco_pidisplay_core_system_InputDeviceManager_stopMonitor
  (JNIEnv *, jclass);

/*
 * Class:     com_ibasco_pidisplay_core_system_InputDeviceManager
 * Method:    queryDevice
 * Signature: (Ljava/lang/String;)Lcom/ibasco/pidisplay/core/system/InputDevice;
 */
JNIEXPORT jobject JNICALL Java_com_ibasco_pidisplay_core_system_InputDeviceManager_queryDevice
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_ibasco_pidisplay_core_system_InputDeviceManager
 * Method:    open
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_ibasco_pidisplay_core_system_InputDeviceManager_open
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_ibasco_pidisplay_core_system_InputDeviceManager
 * Method:    close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_ibasco_pidisplay_core_system_InputDeviceManager_close
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_ibasco_pidisplay_core_system_InputDeviceManager
 * Method:    getInputDevices
 * Signature: ()[Lcom/ibasco/pidisplay/core/system/InputDevice;
 */
JNIEXPORT jobjectArray JNICALL Java_com_ibasco_pidisplay_core_system_InputDeviceManager_getInputDevices
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_ibasco_pidisplay_core_system_InputDeviceManager_RawInputEventListener */

#ifndef _Included_com_ibasco_pidisplay_core_system_InputDeviceManager_RawInputEventListener
#define _Included_com_ibasco_pidisplay_core_system_InputDeviceManager_RawInputEventListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
