/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ibasco_pidisplay_core_system_InputDeviceManager */

#ifndef _Included_com_ibasco_pidisplay_core_system_InputDeviceManager
#define _Included_com_ibasco_pidisplay_core_system_InputDeviceManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ibasco_pidisplay_core_system_InputDeviceManager
 * Method:    startInputEventMonitor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ibasco_pidisplay_core_system_InputDeviceManager_startInputEventMonitor
  (JNIEnv *, jclass);

/*
 * Class:     com_ibasco_pidisplay_core_system_InputDeviceManager
 * Method:    stopInputEventMonitor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ibasco_pidisplay_core_system_InputDeviceManager_stopInputEventMonitor
  (JNIEnv *, jclass);

/*
 * Class:     com_ibasco_pidisplay_core_system_InputDeviceManager
 * Method:    refreshDeviceCache
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ibasco_pidisplay_core_system_InputDeviceManager_refreshDeviceCache
  (JNIEnv *, jclass);

/*
 * Class:     com_ibasco_pidisplay_core_system_InputDeviceManager
 * Method:    queryDevice
 * Signature: (Ljava/lang/String;)Lcom/ibasco/pidisplay/core/system/InputDevice;
 */
JNIEXPORT jobject JNICALL Java_com_ibasco_pidisplay_core_system_InputDeviceManager_queryDevice
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_ibasco_pidisplay_core_system_InputDeviceManager
 * Method:    getInputDevices
 * Signature: ()[Lcom/ibasco/pidisplay/core/system/InputDevice;
 */
JNIEXPORT jobjectArray JNICALL Java_com_ibasco_pidisplay_core_system_InputDeviceManager_getInputDevices
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_ibasco_pidisplay_core_system_InputDeviceManager_DeviceStateEventListener */

#ifndef _Included_com_ibasco_pidisplay_core_system_InputDeviceManager_DeviceStateEventListener
#define _Included_com_ibasco_pidisplay_core_system_InputDeviceManager_DeviceStateEventListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_ibasco_pidisplay_core_system_InputDeviceManager_RawInputEventListener */

#ifndef _Included_com_ibasco_pidisplay_core_system_InputDeviceManager_RawInputEventListener
#define _Included_com_ibasco_pidisplay_core_system_InputDeviceManager_RawInputEventListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
