/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ibasco_pidisplay_core_ui_U8g2Interface */

#ifndef _Included_com_ibasco_pidisplay_core_ui_U8g2Interface
#define _Included_com_ibasco_pidisplay_core_ui_U8g2Interface
#ifdef __cplusplus
extern "C" {
#endif
#undef com_ibasco_pidisplay_core_ui_U8g2Interface_COM_4WSPI
#define com_ibasco_pidisplay_core_ui_U8g2Interface_COM_4WSPI 1L
#undef com_ibasco_pidisplay_core_ui_U8g2Interface_COM_3WSPI
#define com_ibasco_pidisplay_core_ui_U8g2Interface_COM_3WSPI 2L
#undef com_ibasco_pidisplay_core_ui_U8g2Interface_COM_6800
#define com_ibasco_pidisplay_core_ui_U8g2Interface_COM_6800 4L
#undef com_ibasco_pidisplay_core_ui_U8g2Interface_COM_8080
#define com_ibasco_pidisplay_core_ui_U8g2Interface_COM_8080 8L
#undef com_ibasco_pidisplay_core_ui_U8g2Interface_COM_I2C
#define com_ibasco_pidisplay_core_ui_U8g2Interface_COM_I2C 16L
#undef com_ibasco_pidisplay_core_ui_U8g2Interface_COM_ST7920SPI
#define com_ibasco_pidisplay_core_ui_U8g2Interface_COM_ST7920SPI 32L
#undef com_ibasco_pidisplay_core_ui_U8g2Interface_COM_UART
#define com_ibasco_pidisplay_core_ui_U8g2Interface_COM_UART 64L
#undef com_ibasco_pidisplay_core_ui_U8g2Interface_COM_KS0108
#define com_ibasco_pidisplay_core_ui_U8g2Interface_COM_KS0108 128L
#undef com_ibasco_pidisplay_core_ui_U8g2Interface_COM_SED1520
#define com_ibasco_pidisplay_core_ui_U8g2Interface_COM_SED1520 256L
/*
 * Class:     com_ibasco_pidisplay_core_ui_U8g2Interface
 * Method:    setup
 * Signature: (Ljava/lang/String;I[B)J
 */
JNIEXPORT jlong JNICALL Java_com_ibasco_pidisplay_core_ui_U8g2Interface_setup
  (JNIEnv *, jclass, jstring, jint, jbyteArray);

/*
 * Class:     com_ibasco_pidisplay_core_ui_U8g2Interface
 * Method:    drawBox
 * Signature: (JIIII)V
 */
JNIEXPORT void JNICALL Java_com_ibasco_pidisplay_core_ui_U8g2Interface_drawBox
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

/*
 * Class:     com_ibasco_pidisplay_core_ui_U8g2Interface
 * Method:    drawBitmap
 * Signature: (JIIII[B)V
 */
JNIEXPORT void JNICALL Java_com_ibasco_pidisplay_core_ui_U8g2Interface_drawBitmap
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jbyteArray);

/*
 * Class:     com_ibasco_pidisplay_core_ui_U8g2Interface
 * Method:    drawCircle
 * Signature: (JIIII)V
 */
JNIEXPORT void JNICALL Java_com_ibasco_pidisplay_core_ui_U8g2Interface_drawCircle
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

/*
 * Class:     com_ibasco_pidisplay_core_ui_U8g2Interface
 * Method:    drawDisc
 * Signature: (JIIII)V
 */
JNIEXPORT void JNICALL Java_com_ibasco_pidisplay_core_ui_U8g2Interface_drawDisc
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

/*
 * Class:     com_ibasco_pidisplay_core_ui_U8g2Interface
 * Method:    drawEllipse
 * Signature: (JIIIII)V
 */
JNIEXPORT void JNICALL Java_com_ibasco_pidisplay_core_ui_U8g2Interface_drawEllipse
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jint);

/*
 * Class:     com_ibasco_pidisplay_core_ui_U8g2Interface
 * Method:    drawFilledEllipse
 * Signature: (JIIIII)V
 */
JNIEXPORT void JNICALL Java_com_ibasco_pidisplay_core_ui_U8g2Interface_drawFilledEllipse
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jint);

/*
 * Class:     com_ibasco_pidisplay_core_ui_U8g2Interface
 * Method:    drawFrame
 * Signature: (JIIII)V
 */
JNIEXPORT void JNICALL Java_com_ibasco_pidisplay_core_ui_U8g2Interface_drawFrame
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

/*
 * Class:     com_ibasco_pidisplay_core_ui_U8g2Interface
 * Method:    drawGlyph
 * Signature: (JIIS)V
 */
JNIEXPORT void JNICALL Java_com_ibasco_pidisplay_core_ui_U8g2Interface_drawGlyph
  (JNIEnv *, jclass, jlong, jint, jint, jshort);

/*
 * Class:     com_ibasco_pidisplay_core_ui_U8g2Interface
 * Method:    drawHLine
 * Signature: (JIII)V
 */
JNIEXPORT void JNICALL Java_com_ibasco_pidisplay_core_ui_U8g2Interface_drawHLine
  (JNIEnv *, jclass, jlong, jint, jint, jint);

/*
 * Class:     com_ibasco_pidisplay_core_ui_U8g2Interface
 * Method:    drawLine
 * Signature: (JIIII)V
 */
JNIEXPORT void JNICALL Java_com_ibasco_pidisplay_core_ui_U8g2Interface_drawLine
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

/*
 * Class:     com_ibasco_pidisplay_core_ui_U8g2Interface
 * Method:    drawPixel
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_ibasco_pidisplay_core_ui_U8g2Interface_drawPixel
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     com_ibasco_pidisplay_core_ui_U8g2Interface
 * Method:    drawRoundedBox
 * Signature: (JIIIII)V
 */
JNIEXPORT void JNICALL Java_com_ibasco_pidisplay_core_ui_U8g2Interface_drawRoundedBox
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jint);

/*
 * Class:     com_ibasco_pidisplay_core_ui_U8g2Interface
 * Method:    drawRoundedFrame
 * Signature: (JIIIII)V
 */
JNIEXPORT void JNICALL Java_com_ibasco_pidisplay_core_ui_U8g2Interface_drawRoundedFrame
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jint);

/*
 * Class:     com_ibasco_pidisplay_core_ui_U8g2Interface
 * Method:    drawString
 * Signature: (JIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ibasco_pidisplay_core_ui_U8g2Interface_drawString
  (JNIEnv *, jclass, jlong, jint, jint, jstring);

/*
 * Class:     com_ibasco_pidisplay_core_ui_U8g2Interface
 * Method:    drawTriangle
 * Signature: (JIIIIII)V
 */
JNIEXPORT void JNICALL Java_com_ibasco_pidisplay_core_ui_U8g2Interface_drawTriangle
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_ibasco_pidisplay_core_ui_U8g2Interface
 * Method:    drawXBM
 * Signature: (JIIII[B)V
 */
JNIEXPORT void JNICALL Java_com_ibasco_pidisplay_core_ui_U8g2Interface_drawXBM
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jbyteArray);

/*
 * Class:     com_ibasco_pidisplay_core_ui_U8g2Interface
 * Method:    drawUTF8
 * Signature: (JIILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_ibasco_pidisplay_core_ui_U8g2Interface_drawUTF8
  (JNIEnv *, jclass, jlong, jint, jint, jstring);

/*
 * Class:     com_ibasco_pidisplay_core_ui_U8g2Interface
 * Method:    getUTF8Width
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_ibasco_pidisplay_core_ui_U8g2Interface_getUTF8Width
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_ibasco_pidisplay_core_ui_U8g2Interface
 * Method:    setFont
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_com_ibasco_pidisplay_core_ui_U8g2Interface_setFont__J_3B
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     com_ibasco_pidisplay_core_ui_U8g2Interface
 * Method:    setFont
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ibasco_pidisplay_core_ui_U8g2Interface_setFont__JLjava_lang_String_2
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_ibasco_pidisplay_core_ui_U8g2Interface
 * Method:    setFontMode
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_ibasco_pidisplay_core_ui_U8g2Interface_setFontMode
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_ibasco_pidisplay_core_ui_U8g2Interface
 * Method:    setFontDirection
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_ibasco_pidisplay_core_ui_U8g2Interface_setFontDirection
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_ibasco_pidisplay_core_ui_U8g2Interface
 * Method:    setFontPosBaseline
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ibasco_pidisplay_core_ui_U8g2Interface_setFontPosBaseline
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ibasco_pidisplay_core_ui_U8g2Interface
 * Method:    setFontPosBottom
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ibasco_pidisplay_core_ui_U8g2Interface_setFontPosBottom
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ibasco_pidisplay_core_ui_U8g2Interface
 * Method:    setFontPosTop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ibasco_pidisplay_core_ui_U8g2Interface_setFontPosTop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ibasco_pidisplay_core_ui_U8g2Interface
 * Method:    setFontPosCenter
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ibasco_pidisplay_core_ui_U8g2Interface_setFontPosCenter
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ibasco_pidisplay_core_ui_U8g2Interface
 * Method:    setFontRefHeightAll
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ibasco_pidisplay_core_ui_U8g2Interface_setFontRefHeightAll
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ibasco_pidisplay_core_ui_U8g2Interface
 * Method:    setFontRefHeightExtendedText
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ibasco_pidisplay_core_ui_U8g2Interface_setFontRefHeightExtendedText
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ibasco_pidisplay_core_ui_U8g2Interface
 * Method:    setFontRefHeightText
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ibasco_pidisplay_core_ui_U8g2Interface_setFontRefHeightText
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ibasco_pidisplay_core_ui_U8g2Interface
 * Method:    setFlipMode
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_ibasco_pidisplay_core_ui_U8g2Interface_setFlipMode
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_ibasco_pidisplay_core_ui_U8g2Interface
 * Method:    setPowerSave
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_ibasco_pidisplay_core_ui_U8g2Interface_setPowerSave
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_ibasco_pidisplay_core_ui_U8g2Interface
 * Method:    setDrawColor
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_ibasco_pidisplay_core_ui_U8g2Interface_setDrawColor
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_ibasco_pidisplay_core_ui_U8g2Interface
 * Method:    initDisplay
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ibasco_pidisplay_core_ui_U8g2Interface_initDisplay
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ibasco_pidisplay_core_ui_U8g2Interface
 * Method:    firstPage
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ibasco_pidisplay_core_ui_U8g2Interface_firstPage
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ibasco_pidisplay_core_ui_U8g2Interface
 * Method:    nextPage
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_ibasco_pidisplay_core_ui_U8g2Interface_nextPage
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ibasco_pidisplay_core_ui_U8g2Interface
 * Method:    getAscent
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_ibasco_pidisplay_core_ui_U8g2Interface_getAscent
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ibasco_pidisplay_core_ui_U8g2Interface
 * Method:    getDescent
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_ibasco_pidisplay_core_ui_U8g2Interface_getDescent
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ibasco_pidisplay_core_ui_U8g2Interface
 * Method:    getMaxCharWidth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_ibasco_pidisplay_core_ui_U8g2Interface_getMaxCharWidth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ibasco_pidisplay_core_ui_U8g2Interface
 * Method:    getMaxCharHeight
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_ibasco_pidisplay_core_ui_U8g2Interface_getMaxCharHeight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ibasco_pidisplay_core_ui_U8g2Interface
 * Method:    sendBuffer
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ibasco_pidisplay_core_ui_U8g2Interface_sendBuffer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ibasco_pidisplay_core_ui_U8g2Interface
 * Method:    clearBuffer
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ibasco_pidisplay_core_ui_U8g2Interface_clearBuffer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ibasco_pidisplay_core_ui_U8g2Interface
 * Method:    clearDisplay
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ibasco_pidisplay_core_ui_U8g2Interface_clearDisplay
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ibasco_pidisplay_core_ui_U8g2Interface
 * Method:    begin
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ibasco_pidisplay_core_ui_U8g2Interface_begin
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ibasco_pidisplay_core_ui_U8g2Interface
 * Method:    getHeight
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_ibasco_pidisplay_core_ui_U8g2Interface_getHeight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ibasco_pidisplay_core_ui_U8g2Interface
 * Method:    getWidth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_ibasco_pidisplay_core_ui_U8g2Interface_getWidth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ibasco_pidisplay_core_ui_U8g2Interface
 * Method:    clear
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ibasco_pidisplay_core_ui_U8g2Interface_clear
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ibasco_pidisplay_core_ui_U8g2Interface
 * Method:    setAutoPageClear
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_ibasco_pidisplay_core_ui_U8g2Interface_setAutoPageClear
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_ibasco_pidisplay_core_ui_U8g2Interface
 * Method:    setBitmapMode
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_ibasco_pidisplay_core_ui_U8g2Interface_setBitmapMode
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_ibasco_pidisplay_core_ui_U8g2Interface
 * Method:    setContrast
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_ibasco_pidisplay_core_ui_U8g2Interface_setContrast
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_ibasco_pidisplay_core_ui_U8g2Interface
 * Method:    setDisplayRotation
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_ibasco_pidisplay_core_ui_U8g2Interface_setDisplayRotation
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_ibasco_pidisplay_core_ui_U8g2Interface
 * Method:    getBuffer
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_ibasco_pidisplay_core_ui_U8g2Interface_getBuffer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ibasco_pidisplay_core_ui_U8g2Interface
 * Method:    getBufferTileWidth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_ibasco_pidisplay_core_ui_U8g2Interface_getBufferTileWidth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ibasco_pidisplay_core_ui_U8g2Interface
 * Method:    getBufferTileHeight
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_ibasco_pidisplay_core_ui_U8g2Interface_getBufferTileHeight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ibasco_pidisplay_core_ui_U8g2Interface
 * Method:    getPageCurrTileRow
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_ibasco_pidisplay_core_ui_U8g2Interface_getPageCurrTileRow
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ibasco_pidisplay_core_ui_U8g2Interface
 * Method:    setPageCurrTileRow
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_ibasco_pidisplay_core_ui_U8g2Interface_setPageCurrTileRow
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_ibasco_pidisplay_core_ui_U8g2Interface
 * Method:    setBufferCurrTileRow
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_ibasco_pidisplay_core_ui_U8g2Interface_setBufferCurrTileRow
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_ibasco_pidisplay_core_ui_U8g2Interface
 * Method:    getBufferCurrTileRow
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_ibasco_pidisplay_core_ui_U8g2Interface_getBufferCurrTileRow
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
