/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ibasco_ucgdisplay_core_u8g2_U8g2EventDispatcher */

#ifndef _Included_com_ibasco_ucgdisplay_core_u8g2_U8g2EventDispatcher
#define _Included_com_ibasco_ucgdisplay_core_u8g2_U8g2EventDispatcher
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
